### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by gabrieloshiro** [jqassistant-contrib/jqassistant-plantuml-rule-plugin#4]
(Please tag as question instead of bug)

I wanted to try out JQAssistant + PlantUML. So I started a project with Spring Initializr, and I added JQAssistant and your plugin.

Maybe I am missing something here, but where should the input files be located? And where will the output files be placed?

Here is a link to my project https://github.com/gabrieloshiro/jqassistant-pov

Thanks

**Comment by DirkMahler** [comment]
The initial setup of jQA with Spring Boot is described in a tutorial, see https://101.jqassistant.org/getting-started-spring-boot-maven/index.html#ProjectSpecificRules.

If you want to use PlantUML as rules (e.g. using a diagram to define concepts) have a look at the [Spring PetClinic demo](https://github.com/buschmais/spring-petclinic/). The interesting part is located in [jqassistant/layer.adoc](https://raw.githubusercontent.com/buschmais/spring-petclinic/master/jqassistant/layer.adoc), have a closer look to the concept with the id layer:LayerDependencyDefinition.
